# Generated by Django 4.2.1 on 2023-06-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submenu',
            old_name='menu',
            new_name='principal',
        ),
    ]
